server:
    port: 8082
spring:
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        generate-ddl: true
    datasource:
        url: jdbc:mysql://localhost:3306/gestionuser?useSSL=false&serverTimezone=UTC
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        

